### ISSUE TITLE
add inventory items

### ISSUE THREAD

**Issue by lavenderaddict** [kida31/untitled-plant-game#139]
- [x] all the harvestable icons that @Sui-nyan 's plants already have plus their descriptions/flavor text
- [x] leaves of each plant (harvested) and their descriptions
- [x] dried leaves of each plant (processed) and their description
- [x] seeds and their description (@Sui-nyan already drew seeds for all the existing plants)

**Comment by Sui-nyan** [comment]
I also drew the items for the plants
We just need someone who would do the description
