### ISSUE TITLE
Move everything* from notion

### ISSUE THREAD

**Issue by felix-schindler** [kida31/untitled-plant-game#27]
\* issue tracker

- [x] move things
- [x] Document our workflow with GitHub, Notion and Discord

**Comment by felix-schindler** [comment]
@kida31 willst du vllt bevor die PR gemergt wird noch die naming conventions und so ins Wiki ergänzen? Sind zwar nicht auf Notion aber würde (meiner Meinung nach) Sinn machen

**Comment by kida31** [comment]
> @kida31 willst du vllt bevor die PR gemergt wird noch die naming conventions und so ins Wiki ergänzen? Sind zwar nicht auf Notion aber würde (meiner Meinung nach) Sinn machen

https://github.com/kida31/untitled-plant-game/wiki/Contributing
