### ISSUE TITLE
Implement currency and faith for player (no features)

### ISSUE THREAD

**Issue by kida31** [kida31/untitled-plant-game#37]
Implement basic currency and faith. Some pointers (not a definitive list)
- Positive numerical values
- Should be easily accessible (read) (from player object or globally)
- "Write" is not specified (maybe directly? or event?)
- emit event/signal when it changes

**Comment by lavenderaddict** [comment]
@VeryUnlucky pls approve and then close hihi

**Comment by VeryUnlucky** [comment]
LGTM
